### ISSUE TITLE
Add Py_HashPointer

### ISSUE THREAD

**Issue by encukou** [capi-workgroup/decisions#1] opened 2023-12-05 11:36 UTC
The WG should decide if it likes `Py_HashPointer` as added here: https://github.com/python/cpython/pull/112096

**Comment by vstinner** [comment] 2023-12-05 17:59
Since I wrote the PR and part of the C API Working Group, I will not vote on this decision.

Other members who are ok with the proposed API can check their checkbox below:

* [ ] Guido Van Rossum @gvanrossum 
* [ ] Irit Katriel @iritkatriel 
* [ ] Steve Dower @zooba 
* [ ] Petr Viktorin @encukou

If you are not fine with it or if you skip the vote, please add a comment to explain why.

It's the first time that I create such checkbox list, I don't know how it works in terms of security. Or maybe each member should just leave a comment with a message like "+1", "LGTM" or something like that?

**Comment by vstinner** [comment] 2023-12-05 18:00
> It's the first time that I create such checkbox list, I don't know how it works in terms of security.

I can click on Guido's checkbox. I don't think that we should rely on checkboxes to count votes, but we can keep the checkboxes just to check if everybody voted.

**Comment by zooba** [comment] 2023-12-05 18:18
The edit history tells you who changed the checkbox. I'm inclined to agree that posting a message with rationale is better anyway.

**Comment by gvanrossum** [comment] 2023-12-06 11:14
> I can click on Guido's checkbox. I don't think that we should rely on checkboxes to count votes, but we can keep the checkboxes just to check if everybody voted.

Presumably only C API WG members can change the checkboxes. I think we can trust each other.

**Comment by iritkatriel** [comment] 2023-12-06 11:34
I don't have a problem with this API but I don't understand why we need both this and `Py_HashDouble`. The issue is for `Py_HashDouble`.

**Comment by vstinner** [comment] 2023-12-06 14:11
I suppose that this API was easy enough for a first vote, thanks for approving it :-) I merged my PR.

**Closed by vstinner** 2023-12-06 14:11 UTC
